name: 'Kubeconform reporter'
description: 'Make a report for Kubeconform results'

branding:
  icon: 'align-left'
  color: 'red'

inputs:
  file:
    required: true
    description: 'Path to Kubeconform JSON results file'
  show-filename:
    required: false
    description: |-
      Show references to filenames that have errors in the report
    default: 'true'
  modes:
    required: false
    description: |-
      A multi-line input with the following values:
      - pr-comment - report will be added as a comment on PR.
      - check - report will be added in a GitHub check.
      - summary - report will be added as a summary.
  token:
    required: true
    description: 'Your GitHub token'
    default: ${{ github.token }}
  fail-on-error:
    required: false
    description: 'Fail the action if errors are found on the report'
    default: 'false'
  comment-pr-on-success:
    required: false
    description: Comment on PR even if there are no findings
    default: 'true'
runs:
  using: node20
  main: dist/index.js
